name: test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
      - uses: actions/checkout@v2
        with:
          repository: mikekazakov/build
          path: bb-src
      - run: |
          cd main
          bootstrap.bat
        shell: cmd
      - run: |
          cd main
          test.bat
        shell: cmd
 