name: test
on: [push]
jobs:
  hello:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
        with:
          path: main
        uses: actions/checkout@v2
        with:
          repository: mikekazakov/build
          path: bb-src
        run: echo "Hello, world!"
